# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bffcf6a8544a41538004c1fa878489051c2ce067017448f74884180bbf67260fbc76410585c604a5c4f2ecf950b9b45a0ecb2406281cc1e0bb4160c9c16da383

test:
  secret_key_base: 4505b54417e97ba25146a798761ef16f685a53f400233f7aed78a00cf04185f582741462243c9b4512192b9e80c3366d363af70fefa53bcfe49f6fca2ed3480e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
